### PR TITLE
Docs-Correspond to the First Milestone of this project 

### PR DESCRIPTION
**Pull request by angelacuahutle**
Docs-Correspond to the first Milestone of this project, where I did the following:

|x| Watch this video about Entity Relationship Diagram (ERD).
|x|  Watch this video about Primary and Foreign Keys.
|x|  Create your own ERD. You can use an online tool to do that or draw it on the piece of paper and take a photo of it.

|x| Put a file with your ERD in the “docs” directory in your repo.

### CODE REVIEW

**Review by carlos-ssh — CHANGES_REQUESTED** [review]
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
In your ERD DIAGRAM, it's required to do some changes:
- Your like table, it's missing foreign keys for user and post ID.
Kindly fix it.


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

[OPTIONAL]
- Display your ERD file in your README File.
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by angelacuahutle** [comment]
Made the appropriate changes to the diagram. 
Thanks

**Review by george-shammar — APPROVED** [review]
Hi @angelacuahutle , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by angelacuahutle** [comment]
Dear TSE

I have covered Milestone 5: Friendships v1. 

For this task, I have created a model with associations and all requested features for friendships.
I also included their respective unit and integration test. 

Thanks

**Review by eliasecasta — CHANGES_REQUESTED** [review]
## Status:  Invalid 🔴 

Hi, @angelacuahutle, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is using an old pull request for a different milestone, please create a new one with linters set in order to check this milestone as indicated by Microverse:

image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Pull request closed without merging**
